# queue rule 'default': `allow_queue_branch_edit` was turned off. It now requires `merge_method: merge-batch` or `merge_method: fast-forward`.
extends: MH0386
queue_rules:
  - name: default
    update_method: rebase
    allow_queue_branch_edit: false
    queue_conditions:
      - and:
          - "check-success = DeepSource: Secrets"
          - "check-success = DeepSource: Python"
          - check-success = CodeQL
          - check-success = CodeFactor
          - check-success = GitGuardian Security Checks
          - check-success = SonarCloud
          - check-success = Check Dependency Compatibility
merge_protections_settings:
  reporting_method: check-runs
