pull_request_rules:
  - name: Automatically merge valid PRs
    conditions:
      - or:
          - author = github-actions[bot]
          - author = dependabot[bot]
          - author = renovate[bot]
          - author = MH0386
      - and:
          - check-success = SonarCloud
          - check-success = CodeQL
          - check-success = Trunk Code Quality
    actions:
      queue:
  - name: Add a queue label when PR is queued
    description: Toggle the queue label when a pull request is (un)queued.
    conditions:
      - queue-position > 0
    actions:
      label:
        toggle:
          - merge-queued
  - name: Notify when a PR is removed from the queue
    description: Notify the PR author when its pull request is removed from the merge queue.
    conditions:
      - queue-dequeue-reason != none
      - queue-dequeue-reason != pr-merged
    actions:
      comment:
        message: >
          Hey @{{author}}, your pull request has been dequeued due to the
          following reason: {{queue_dequeue_reason}}.

          Sorry about that, but you can requeue the PR by using `@mergifyio
          requeue` if you think this was a mistake.
queue_rules:
  - queue_branch_merge_method: fast-forward
    allow_queue_branch_edit: true
    update_method: merge
    name: default
