name: Automatic merge
conditions:
  - check-success>=1
actions:
  merge:
    method: merge
queue_rules:
  - queue_branch_merge_method: fast-forward
    allow_queue_branch_edit: true
    update_method: merge
    name: default
