pull_request_rules:
  - name: Automatically queue valid Bot PRs
    conditions:
      - author != MH0386
    actions:
      queue:
  - name: Request review from me
    description: Request review from me when checks are green.
    conditions:
      - author = MH0386
      - -closed
      - "#approved-reviews-by = 0"
      - "#changes-requested-reviews-by = 0"
      - "review-requested != MH0386"
    actions:
      request_reviews:
        users:
          - MH0386
  - name: Add a queue label when PR is queued
    description: Toggle the queue label when a pull request is (un)queued.
    conditions:
      - queue-position > 0
    actions:
      label:
        toggle:
          - merge-queued
  - name: Notify when a PR is removed from the queue
    description: Notify the PR author when its pull request is removed from the merge queue.
    conditions:
      - queue-dequeue-reason != none
      - queue-dequeue-reason != pr-merged
    actions:
      comment:
        message: >
          Hey @{{author}}, your pull request has been dequeued due to the
          following reason: {{queue_dequeue_reason}}.

          Sorry about that, but you can requeue the PR by using `@mergifyio
          requeue` if you think this was a mistake.
queue_rules:
  - name: default
    queue_branch_merge_method: fast-forward
    allow_queue_branch_edit: true
    update_method: merge
    queue_conditions:
      - and:
          - "check-success = DeepSource: Secrets"
          - "check-success = DeepSource: Dart Analyze"
          - check-success = CodeRabbit
          - check-success = CodeFactor
          - check-success = GitGuardian Security Checks
          - check-success = SonarCloud
          - check-success = Trunk Check
          - check-success = Flutter Dependency Consistency
