[project]
name = "mh0386githubio"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.11"
authors = [
  { name = "Mohamed Hisham Abdelzaher", email = "mohamed.hisham.abdelzaher@gmail.com" },
]
dependencies = ["flet==0.27.6", "flet-webview>=0.1.0"]

[tool.flet]
org = "com.mh0386"
product = "mh0386githubio"
company = "MH0386"
copyright = "Copyright (C) 2025 by MH0386"

[tool.flet.app]
path = "src"

[dependency-groups]
dev = ["flet[all]>=0.27.6", "ruff>=0.11.11", "ty>=0.0.1a6"]
