[project]
name = "mh0386githubio"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.11"
authors = [
    { name = "Mohamed Hisham Abdelzaher", email = "mohamed.hisham.abdelzaher@gmail.com" }
]
dependencies = [
  "flet==0.27.6",
  "flet-webview>=0.1.0",
]

[tool.flet]
# org name in reverse domain name notation, e.g. "com.mycompany".
# Combined with project.name to build bundle ID for iOS and Android apps
org = "com.mh0386"

# project display name that is used as an app title on Android and iOS home screens,
# shown in window titles and about app dialogs on desktop.
product = "mh0386githubio"

# company name to display in about app dialogs
company = "MH0386"

# copyright text to display in about app dialogs
copyright = "Copyright (C) 2025 by MH0386"

[tool.flet.app]
path = "src"

[dependency-groups]
dev = [
    "flet[all]>=0.27.6",
]
