name: Deploy to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main
permissions:
  contents: write
  pages: write
  id-token: write
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true
jobs:
  build_web:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Cache .web
        uses: actions/cache@v4
        with:
          path: .web
          key: ${{ runner.os }}-reflex-${{ hashFiles('**/uv.lock') }}
          restore-keys: ${{ runner.os }}-reflex-
      - name: Install uv
        uses: astral-sh/setup-uv@bd01e18f51369d5a26f1651c3cb451d3417e3bba # v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          activate-environment: true
      - name: Install Dependencies
        run: uv sync --frozen
      - name: Build
        run: uv run reflex export --frontend-only --no-zip --env prod
      - run: ls -a
      - name: Upload artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3
        with:
          path: ./.web/_static/
  deploy_web:
    name: Deploy Web
    runs-on: ubuntu-latest
    needs: build_web
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4
