name: Devbox
on:
    schedule:
        - cron: "0 0 * * *"
    push:
        branches:
            - main
jobs:
    devbox:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install devbox
              uses: jetify-com/devbox-install-action@v0.12.0
              with:
                enable-cache: 'true'
            - name: Update Package
              run: devbox update
