name: Testing with devbox

on: push

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install devbox
              uses: jetify-com/devbox-install-action@v0.11.0
            - name: Run a script called test
              run: devbox run test
            - name: Update Package
              run: devbox update
