name: Sync Docs
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 8 * * 1-5"
permissions:
  contents: write
  pages: write
jobs:
  sync_docs:
    name: Sync Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Git Config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Download Docs
        uses: robinraju/release-downloader@v1.12
        with:
          latest: true
          fileName: "resume.pdf"
          out-file-path: "assets/docs/"
          repository: "MH0386/MH0386"
      - name: Commit & Push
        continue-on-error: true
        run: |
          git add assets/docs/
          git commit -m "Update Docs"
          git pull
          git push
