name: Sync Docs
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - .github/workflows/sync.yml
  schedule:
    - cron: "0 8 * * 1-5"
permissions:
  contents: write
  pages: write
jobs:
  sync_docs:
    name: Sync Docs to ${{ matrix.branch }}
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    strategy:
      fail-fast: false
      matrix:
        branch: [main, gh-pages]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}
          fetch-depth: 0
      - name: Git Config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Download Docs
        uses: robinraju/release-downloader@v1.12
        with:
          latest: true
          fileName: "resume.pdf"
          out-file-path: "data/docs/"
          repository: "MH0386/MH0386"
      - name: Commit & Push to ${{ matrix.branch }}
        continue-on-error: true
        run: |
          git add data/docs/
          git commit -m "Update Docs"
          git pull
          git push
