name: Upgrade Trunk Check
on:
  workflow_dispatch:
  schedule:
    - cron: 0 8 * * 1-5
permissions:
  contents: write
  pull-requests: write
  issues: write
jobs:
  trunk_upgrade:
    name: Upgrade Trunk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Trunk Upgrade
        uses: trunk-io/trunk-action/upgrade@v1
