name: Upgrade Trunk Check
on:
  workflow_dispatch:
  schedule:
    - cron: 0 8 * * 1-5
permissions:
  contents: write
  pull-requests: write
  issues: write
jobs:
  trunk_upgrade:
    name: Upgrade Trunk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Trunk Upgrade
        uses: trunk-io/trunk-action/upgrade@04ba50e7658c81db7356da96657e6e77f220bfa3 # v1
