name: Upgrade Trunk Check
on:
  workflow_dispatch:
  schedule:
    - cron: 0 8 * * 1-5
permissions:
  contents: write
  pull-requests: write
  issues: write
jobs:
  trunk_upgrade:
    name: Upgrade Trunk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Trunk Upgrade
        uses: trunk-io/trunk-action/upgrade@75699af9e26881e564e9d832ef7dc3af25ec031b # v1
